<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1x81FVJ\App_KernelLiveDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1x81FVJ/App_KernelLiveDebugContainer.php') {
    touch(__DIR__.'/Container1x81FVJ.legacy');

    return;
}

if (!\class_exists(App_KernelLiveDebugContainer::class, false)) {
    \class_alias(\Container1x81FVJ\App_KernelLiveDebugContainer::class, App_KernelLiveDebugContainer::class, false);
}

return new \Container1x81FVJ\App_KernelLiveDebugContainer([
    'container.build_hash' => '1x81FVJ',
    'container.build_id' => '843be1a1',
    'container.build_time' => 1682516128,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1x81FVJ');
