services:
    trinitysliderbundle_show:
        class: \App\Trinity\SliderBundle\Controller\SliderController
        public: true
        arguments: ["@translator", "@service_container", "@trinity.mailer"]
        calls:
            - [setContainer, ["@service_container"]]

    trinitysliderbundle_link:
        class: \App\Trinity\SliderBundle\Controller\SliderController
        public: true
        arguments: ["@translator", "@service_container", "@trinity.mailer"]
        calls:
            - [setContainer, ["@service_container"]]
