framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    esi: { enabled: true }

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: session.handler.native_file
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 3600 # 1 hour (default)
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'

    #esi: true
    #fragments: true
    php_errors:
        log: true

    translator:      { fallbacks: ["nl"] }
    default_locale:  "nl"

    error_controller: App\CmsBundle\Controller\ErrorController::show