nelmio_api_doc:
    documentation:
        info:
            title: "Trinity API"
            description: "The new best thing in web"
            version: 2.0.0
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    description: 'Value: Bearer {jwt}'
                    name: Authorization
                    in: header
        security:
            - Bearer: []
    areas:
        path_patterns: # an array of regexps
            - ^/api(?!/doc$)
        # host_patterns:
            # - ^post\.