twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    auto_reload: true
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'
    form_themes: ['@Cms/form.html.twig']
    globals:
        trinity: "%trinity_title%"
        trinity_url: "%trinity_url%"
        trinity_support: "%trinity_support_email%"
        company: "%trinity_company%"
        company_url: "%trinity_company_url%"