version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: symfony_app:latest
    container_name: symfony_app
    ports:
      - "8000:443"
    volumes:
      - ./localhost.crt:/etc/ssl/certs/localhost.crt
      - ./localhost.key:/etc/ssl/private/localhost.key
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://neutraleco_web01:YES@database:3306/neutraleco_web01
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=database
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=YES
      - MYSQL_DATABASE=neutraleco_web01
      - MYSQL_USER=neutraleco_web01
      - MYSQL_PASSWORD=YES
    command: '--default-authentication-plugin=mysql_native_password'

volumes:
  db_data: