<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5E7GAo9\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5E7GAo9/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container5E7GAo9.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container5E7GAo9\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container5E7GAo9\App_KernelProdContainer([
    'container.build_hash' => '5E7GAo9',
    'container.build_id' => '68cd2bcb',
    'container.build_time' => 1697651395,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5E7GAo9');
