services:
    trinityformsbundle_show:
        class: \App\Trinity\FormsBundle\Controller\FormsController
        public: true
        arguments: ["@translator", "@service_container", "@trinity.mailer"]
        calls:
            - [setContainer, ["@service_container"]]

    trinityformsbundle_link:
        class: \App\Trinity\FormsBundle\Controller\FormsController
        public: true
        arguments: ["@translator", "@service_container", "@trinity.mailer"]
        calls:
            - [setContainer, ["@service_container"]]
