<?php

namespace App\CmsBundle\Repository;

/**
 * ClientdomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientdomainRepository extends \Doctrine\ORM\EntityRepository
{
        public function findByBundle($count = false, $bundleName = ''){
                $sql = "SELECT      " . ($count ? "L.domain,COUNT(L)" : "L") . "
                FROM        CmsBundle:Clientdomain AS L
                JOIN        L.requests AS R
                WHERE           L.bundles LIKE '%" . '"' . $bundleName . '"' . "%'
                " . ($count ? "GROUP BY L.domain" : "") . "
                ";
                if($count){
                        $c = 0;
                        $r = $this->getEntityManager()->createQuery($sql)->getScalarResult();        
                        return count($r);
                }
                return $this->getEntityManager()->createQuery($sql)->getResult();
        }
	public function getByTag($Tag){
		$sql = "SELECT      L
                FROM        CmsBundle:Clientdomain AS L
                JOIN        L.tags AS R
                WHERE       R.id = " . $Tag->getId() . "
                ";
                return $this->getEntityManager()->createQuery($sql)->getResult();
	}
}
