<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMUg34xE\App_KernelLiveDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMUg34xE/App_KernelLiveDebugContainer.php') {
    touch(__DIR__.'/ContainerMUg34xE.legacy');

    return;
}

if (!\class_exists(App_KernelLiveDebugContainer::class, false)) {
    \class_alias(\ContainerMUg34xE\App_KernelLiveDebugContainer::class, App_KernelLiveDebugContainer::class, false);
}

return new \ContainerMUg34xE\App_KernelLiveDebugContainer([
    'container.build_hash' => 'MUg34xE',
    'container.build_id' => '2779cc01',
    'container.build_time' => 1682516150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMUg34xE');
