# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/5.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true                  # If TOTP authentication should be enabled, default false
        server_name: Easify       # Server name used in QR code
        issuer: Easify TOTP            # Issuer name used in QR code
        window: 1                      # How many codes before/after the current one would be accepted as valid
        # parameters:                    # Additional parameters added in the QR code
        #     image: 'https://my-service/img/logo.png'
        template: '@Cms/login/2fa.html.twig'   # Template used to render the authentication form
    trusted_device:
        enabled: true                 # If the trusted device feature should be enabled
        lifetime: 5184000              # Lifetime of the trusted device token
        extend_lifetime: true         # Automatically extend lifetime of the trusted cookie on re-login
        cookie_name: trusted_device    # Name of the trusted device cookie
        cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
        cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax" or "strict"
        # cookie_domain: ".example.com"  # Domain to use when setting the cookie, fallback to the request domain if not set
        cookie_path: "/"               # Path to use when setting the cookie
    backup_codes:
        enabled: true  # If the backup code feature should be enabled