<?php

namespace Proxies\__CG__\App\Trinity\FormsBundle\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Form extends \App\Trinity\FormsBundle\Entity\Form implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'id', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'label', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'intro', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'auto_response', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'auto_response_text', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'auto_response_subject', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'hide_clear_button', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'dateStart', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'dateEdit', 'questions', 'answers', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'mails', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'language', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'settings', 'floating_labels', 'active_campaign', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'active_campaign_listid', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'active_campaign_key', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'active_campaign_url', 'mail_reply_to', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'mailer_listid', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'mail_interal_username'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'id', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'label', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'intro', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'auto_response', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'auto_response_text', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'auto_response_subject', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'hide_clear_button', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'dateStart', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'dateEdit', 'questions', 'answers', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'mails', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'language', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'settings', 'floating_labels', 'active_campaign', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'active_campaign_listid', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'active_campaign_key', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'active_campaign_url', 'mail_reply_to', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'mailer_listid', '' . "\0" . 'App\\Trinity\\FormsBundle\\Entity\\Form' . "\0" . 'mail_interal_username'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Form $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLabel($label)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLabel', [$label]);

        return parent::setLabel($label);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabel', []);

        return parent::getLabel();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntro($intro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntro', [$intro]);

        return parent::setIntro($intro);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntro', []);

        return parent::getIntro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateStart($dateStart)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateStart', [$dateStart]);

        return parent::setDateStart($dateStart);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateStart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateStart', []);

        return parent::getDateStart();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEdit($dateEdit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEdit', [$dateEdit]);

        return parent::setDateEdit($dateEdit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEdit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEdit', []);

        return parent::getDateEdit();
    }

    /**
     * {@inheritDoc}
     */
    public function addQuestion(\App\Trinity\FormsBundle\Entity\Question $question)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuestion', [$question]);

        return parent::addQuestion($question);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQuestion(\App\Trinity\FormsBundle\Entity\Question $question)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQuestion', [$question]);

        return parent::removeQuestion($question);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestions', []);

        return parent::getQuestions();
    }

    /**
     * {@inheritDoc}
     */
    public function addAnswer(\App\Trinity\FormsBundle\Entity\Answer $answer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAnswer', [$answer]);

        return parent::addAnswer($answer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAnswer(\App\Trinity\FormsBundle\Entity\Answer $answer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAnswer', [$answer]);

        return parent::removeAnswer($answer);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnswers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnswers', []);

        return parent::getAnswers();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage(\App\CmsBundle\Entity\Language $language = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoResponse($autoResponse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoResponse', [$autoResponse]);

        return parent::setAutoResponse($autoResponse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutoResponse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutoResponse', []);

        return parent::getAutoResponse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoResponseText($autoResponseText)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoResponseText', [$autoResponseText]);

        return parent::setAutoResponseText($autoResponseText);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutoResponseText()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutoResponseText', []);

        return parent::getAutoResponseText();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoResponseSubject($autoResponseSubject)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoResponseSubject', [$autoResponseSubject]);

        return parent::setAutoResponseSubject($autoResponseSubject);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutoResponseSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutoResponseSubject', []);

        return parent::getAutoResponseSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setMails($mails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMails', [$mails]);

        return parent::setMails($mails);
    }

    /**
     * {@inheritDoc}
     */
    public function getMails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMails', []);

        return parent::getMails();
    }

    /**
     * {@inheritDoc}
     */
    public function setHideClearButton($hideClearButton = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHideClearButton', [$hideClearButton]);

        return parent::setHideClearButton($hideClearButton);
    }

    /**
     * {@inheritDoc}
     */
    public function getHideClearButton()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHideClearButton', []);

        return parent::getHideClearButton();
    }

    /**
     * {@inheritDoc}
     */
    public function setSettings(\App\CmsBundle\Entity\Settings $settings = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSettings', [$settings]);

        return parent::setSettings($settings);
    }

    /**
     * {@inheritDoc}
     */
    public function getSettings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSettings', []);

        return parent::getSettings();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailReplyTo($mailReplyTo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailReplyTo', [$mailReplyTo]);

        return parent::setMailReplyTo($mailReplyTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailReplyTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailReplyTo', []);

        return parent::getMailReplyTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailInteralUsername($mailInteralUsername = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailInteralUsername', [$mailInteralUsername]);

        return parent::setMailInteralUsername($mailInteralUsername);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailInteralUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailInteralUsername', []);

        return parent::getMailInteralUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setFloatingLabels($floating_labels = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFloatingLabels', [$floating_labels]);

        return parent::setFloatingLabels($floating_labels);
    }

    /**
     * {@inheritDoc}
     */
    public function getFloatingLabels()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFloatingLabels', []);

        return parent::getFloatingLabels();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveCampaign($activeCampaign = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveCampaign', [$activeCampaign]);

        return parent::setActiveCampaign($activeCampaign);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveCampaign()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveCampaign', []);

        return parent::getActiveCampaign();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveCampaignListid($activeCampaignListid = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveCampaignListid', [$activeCampaignListid]);

        return parent::setActiveCampaignListid($activeCampaignListid);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveCampaignListid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveCampaignListid', []);

        return parent::getActiveCampaignListid();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveCampaignKey($activeCampaignKey = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveCampaignKey', [$activeCampaignKey]);

        return parent::setActiveCampaignKey($activeCampaignKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveCampaignKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveCampaignKey', []);

        return parent::getActiveCampaignKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setActiveCampaignUrl(string $activeCampaignUrl = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActiveCampaignUrl', [$activeCampaignUrl]);

        return parent::setActiveCampaignUrl($activeCampaignUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveCampaignUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveCampaignUrl', []);

        return parent::getActiveCampaignUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getMailerListid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailerListid', []);

        return parent::getMailerListid();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailerListid(string $mailer_listid): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailerListid', [$mailer_listid]);

        parent::setMailerListid($mailer_listid);
    }

}
